version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: api/produtos
    container_name: api_produtos
    ports:
      - 4567:4567
    environment:
      RACK_ENV: production
    command: bundle exec puma -b tcp://0.0.0.0 -p 4567 -w 0 -q --redirect-stderr /dev/null
    restart: always
    deploy:
      mode: replicated
      replicas: 20