version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: api/produtos
    container_name: api_produtos
    ports:
      - 4567:4567
    volumes:
      - '.:/app'
    environment:
      RACK_ENV: production
    command: bundle exec puma -b tcp://0.0.0.0 -p 4567 -w 1 -q --redirect-stderr /dev/null
    restart: always
    deploy:
      mode: replicated
      replicas: 4
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: codificator
      POSTGRES_PASSWORD: adminastor