version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: api/produtos
    container_name: api_produtos
    ports:
      - 4567:4567
    volumes:
      - '.:/app'
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: codificator
      POSTGRES_PASSWORD: adminastor